version: "3.9"
services:
    site:
        build:
            context: ./site
            args:
                PORT: "8080"
                SELF_LOC: "http://blairsec2022_xss_site:8080/"
        container_name: blairsec2022_xss_site
        deploy:
            restart_policy:
                condition: "on-failure"
        env_file: ./site.env
        expose:
            - "8080"
        healthcheck:
            test:
                ["CMD", "timeout", "10s", "curl", "-f", "http://localhost:8080"]
            interval: 1m
            timeout: 10s
            retries: 3
            start_period: 30s
        ports:
            - "${WEB_PORT}:8080"
        stop_grace_period: 3s

    admin_bot:
        cap_add:
            - SYS_ADMIN
        build:
            context: ./admin-bot
        ports: 
            - "6970:8080"            
        deploy:
            replicas: ${ADMIN_REPLICAS}
            restart_policy:
                condition: "on-failure"
        env_file: ./admin_bot.env
        stop_grace_period: 3s
                    
        #     admin_bot:
        #         build:
        #             context: ./admin-bot
        #             args:
        #                 SOCKDIR: "/tmp/socks/"
        #         deploy:
        #             replicas: ${ADMIN_REPLICAS}
        #             restart_policy:
        #                 condition: "on-failure"
        #         env_file: ./site.env
        #         env_file: ./admin_bot.env
        #         stop_grace_period: 3s
        #         volumes:
        #             - /tmp/dockersharedsocks:/tmp/socks
